
const DOMAIN_NAME = "Venta de Accesorios Deportivos";
const itemName = "Raqueta de Tenis";
const itemCategory = "Equipo de Tenis";
const itemPrice = 150; 
const isInStock = true; 
const currentDiscount = null; 
console.log("===========================");
console.log(`FICHA DE DATOS: ${DOMAIN_NAME}`);
console.log("===========================");
console.log("");
console.log(`Nombre:    ${itemName}`);
console.log(`Categoría: ${itemCategory}`);
console.log(`Precio:    $${itemPrice}`);
console.log(`En Stock:  ${isInStock}`);
console.log("");
console.log("--- Tipos de datos ---");
console.log("typeof itemName:     ", typeof itemName);
console.log("typeof itemCategory: ", typeof itemCategory);
console.log("typeof itemPrice:    ", typeof itemPrice);
console.log("");
console.log("--- Conversiones ---");
const priceAsText = String(itemPrice);
console.log("Precio como texto:", priceAsText);
console.log("typeof (convertido):", typeof priceAsText);
console.log("");
console.log("--- Valor nulo ---");
console.log("typeof null:", typeof currentDiscount);    
console.log("¿Es null?:", currentDiscount === null);    
console.log("");
console.log("===========================");
console.log("FIN DE FICHA");
console.log("===========================");
